export const GATE_PASS_EVENTS = new Set([
    'RULE_PACK_LOADED',
    'PREFLIGHT_CLASSIFIED',
    'COMPILE_GATE_PASSED',
    'REVIEW_GATE_PASSED',
    'REVIEW_GATE_PASSED_WITH_OVERRIDE',
    'DOC_IMPACT_ASSESSED',
    'FULL_SUITE_VALIDATION_PASSED',
    'FULL_SUITE_VALIDATION_WARNED',
    'FULL_SUITE_VALIDATION_SKIPPED',
    'COMPLETION_GATE_PASSED'
]);

export const GATE_FAIL_EVENTS = new Set([
    'RULE_PACK_LOAD_FAILED',
    'PREFLIGHT_FAILED',
    'COMPILE_GATE_FAILED',
    'REVIEW_GATE_FAILED',
    'DOC_IMPACT_ASSESSMENT_FAILED',
    'FULL_SUITE_VALIDATION_FAILED',
    'COMPLETION_GATE_FAILED'
]);
