/** Browser-side dashboard script fragment (cleanup settings tab). */
export const UI_DASHBOARD_CLIENT_CLEANUP = [
    'const CLEANUP_FIELD_INPUT_IDS = {',
    '  daily_maintenance_enabled: "cleanup-daily-enabled",',
    '  daily_maintenance_max_tasks_per_run: "cleanup-max-tasks",',
    '  eligible_older_than_days: "cleanup-older-than-days",',
    '  keep_latest_tasks: "cleanup-keep-latest",',
    '  daily_maintenance_dry_run: "cleanup-daily-dry-run",',
    '  purge_require_confirm: "cleanup-purge-require-confirm",',
    '  healthy_done_compact_after_days: "cleanup-healthy-compact-days",',
    '  problem_tasks_compress_after_days: "cleanup-problem-compress-days"',
    '};',
    'let currentCleanupPayload = null;',
    'let currentCleanupResult = null;',
    'function cleanupText(id, field, fallback) {',
    '  return localizedField(cleanupSettingTextPacks, id, field, fallback);',
    '}',
    'function cleanupBooleanLabel(value) {',
    '  return cleanupText(value ? "value_true" : "value_false", "label", String(value));',
    '}',
    'function cleanupFieldValue(fieldKey) {',
    '  const inputId = CLEANUP_FIELD_INPUT_IDS[fieldKey];',
    '  const input = document.getElementById(inputId);',
    '  if (!input) return null;',
    '  if (input.tagName === "SELECT") {',
    '    return input.value === "true";',
    '  }',
    '  if (input.type === "checkbox") {',
    '    return input.checked;',
    '  }',
    '  return input.value;',
    '}',
    'function cleanupSettingsPatch(fieldKey) {',
    '  const patch = {};',
    '  patch[fieldKey] = cleanupFieldValue(fieldKey);',
    '  return patch;',
    '}',
    'function renderCleanupResult(result) {',
    '  currentCleanupResult = result;',
    '  const actionId = result.action_id || "";',
    '  const label = cleanupResultLabel(actionId);',
    '  const summary = cleanupResultSummary(result);',
    '  cleanupStatusNode.innerHTML = "<section class=\\"command-preview-panel\\">"',
    '    + "<div class=\\"command-preview-main\\"><strong>" + safe(label) + "</strong></div>"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(cleanupResultStatusLabel()) + "<code>" + safe(summary) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + cleanupReportHighlights(result)',
    '    + cleanupOutputBlock(result)',
    '    + outputBlock("stderr", result.stderr)',
    '    + (result.error ? "<p class=\\"error\\">" + safe(result.error) + "</p>" : "")',
    '    + "</section>";',
    '  focusCleanupResultPanel();',
    '}',
    'function cleanupOutputBlock(result) {',
    '  if (!result || !result.stdout) return "";',
    '  const actionId = result.action_id || "";',
    '  const label = actionId === "cleanup-preview-custom" || actionId === "cleanup-apply-custom"',
    '    ? cleanupReportLabel()',
    '    : "stdout";',
    '  return outputBlock(label, result.stdout);',
    '}',
    'function cleanupReportLabel() {',
    '  return cleanupText("cleanup_report", "label", "Cleanup report");',
    '}',
    'function cleanupReportHighlights(result) {',
    '  if (!result || (result.action_id !== "cleanup-preview-custom" && result.action_id !== "cleanup-apply-custom")) return "";',
    '  const stdout = cleanupPlainOutput(result.stdout);',
    '  if (!stdout.trim()) return "";',
    '  const isApply = result.action_id === "cleanup-apply-custom";',
    '  const previewTasks = cleanupFirstMatch(stdout, /^RuntimeRetentionPreviewTasks:\\s*(\\d+)$/m);',
    '  const eligibleNow = cleanupFirstMatch(stdout, /^RuntimeRetentionEligibleNow:\\s*(\\d+)$/m);',
    '  const freeValue = cleanupFirstMatch(stdout, isApply ? /^Freed:\\s*(.+)$/m : /^Would free:\\s*(.+)$/m);',
    '  const removePattern = isApply ? /^Removed \\(([^)]+)\\):\\s*(\\d+)$/gm : /^Would remove \\(([^)]+)\\):\\s*(\\d+)$/gm;',
    '  const removeLines = [];',
    '  let removeTotal = 0;',
    '  for (const match of stdout.matchAll(removePattern)) {',
    '    removeLines.push(match[1] + ": " + match[2]);',
    '    removeTotal += Number(match[2]);',
    '  }',
    '  const parts = [];',
    '  if (previewTasks !== null) parts.push(cleanupReportText("previewTasks") + ": " + previewTasks);',
    '  if (eligibleNow !== null) parts.push(cleanupReportText("eligibleNow") + ": " + eligibleNow);',
    '  if (removeLines.length > 0) parts.push(cleanupReportText(isApply ? "removed" : "wouldRemove") + ": " + String(removeTotal) + " (" + removeLines.join(", ") + ")");',
    '  if (freeValue !== null) parts.push(cleanupReportText(isApply ? "freed" : "wouldFree") + ": " + freeValue);',
    '  if (parts.length === 0) return "";',
    '  return "<div class=\\"command-preview-meta cleanup-report-highlights\\">" + parts.map((part) => "<span>" + safe(part) + "</span>").join("") + "</div>";',
    '}',
    'function cleanupPlainOutput(value) {',
    '  return String(value || "").replace(/\\u001b\\[[0-?]*[ -/]*[@-~]/g, "");',
    '}',
    'function cleanupFirstMatch(value, pattern) {',
    '  const match = String(value || "").match(pattern);',
    '  return match ? match[1] : null;',
    '}',
    'function cleanupReportText(key) {',
    '  const labels = {',
    '    previewTasks: cleanupText("report_preview_tasks", "label", "Preview candidates"),',
    '    eligibleNow: cleanupText("report_eligible_now", "label", "Eligible now"),',
    '    wouldRemove: cleanupText("report_would_remove", "label", "Would remove"),',
    '    wouldFree: cleanupText("report_would_free", "label", "Would free"),',
    '    removed: cleanupText("report_removed", "label", "Removed"),',
    '    freed: cleanupText("report_freed", "label", "Freed")',
    '  };',
    '  return labels[key] || key;',
    '}',
    'function cleanupResultLabel(actionId) {',
    '  if (actionId === "cleanup-settings") return cleanupText("tab_intro", "label", t("cleanupSettingsTab"));',
    '  if (actionId === "cleanup-preview-custom") return cleanupRunPreviewLabel() + " — " + cleanupText("manual_runtime_cleanup", "label", "Manual runtime cleanup");',
    '  if (actionId === "cleanup-apply-custom") return cleanupRunApplyLabel() + " — " + cleanupText("manual_runtime_cleanup", "label", "Manual runtime cleanup");',
    '  if (actionId === "cleanup-task-purge") return cleanupText("purge_task_button", "label", "Clean task runtime artifacts");',
    '  return actionId || t("cleanupSettingsTab");',
    '}',
    'function cleanupResultSummary(result) {',
    '  const exitCode = result && typeof result.exit_code === "number" ? result.exit_code : null;',
    '  if (result && result.status === "executed" && (result.http_ok === true || exitCode === 0) && (exitCode === null || exitCode === 0)) return "OK";',
    '  const outcome = cleanupResultOutcomeText(result, exitCode);',
    '  const raw = String((result && (result.stderr || result.error || result.stdout || result.message)) || "");',
    '  if (!raw.trim()) return outcome;',
    '  const normalized = raw.replace(/\\s+/g, " ").trim();',
    '  return outcome + ": " + (normalized.length > 240 ? normalized.slice(0, 240) + "..." : normalized);',
    '}',
    'function cleanupResultOutcomeText(result, exitCode) {',
    '  if (!result) return "-";',
    '  if (result.http_ok === false) return resultStatusText("unavailable");',
    '  if (typeof exitCode === "number" && exitCode !== 0) return "Exit code " + String(exitCode);',
    '  return resultStatusText(result.status);',
    '}',
    'function focusCleanupResultPanel() {',
    '  if (!cleanupStatusNode) return;',
    '  if (typeof cleanupStatusNode.setAttribute === "function") {',
    '    cleanupStatusNode.setAttribute("tabindex", "-1");',
    '  }',
    '  if (typeof cleanupStatusNode.scrollIntoView === "function") {',
    '    cleanupStatusNode.scrollIntoView({ behavior: "smooth", block: "start" });',
    '  }',
    '  if (typeof cleanupStatusNode.focus === "function") {',
    '    cleanupStatusNode.focus({ preventScroll: true });',
    '  }',
    '}',
    'function cleanupRunSelectionFromInputs() {',
    '  return {',
    '    eligible_older_than_days: cleanupFieldValue("eligible_older_than_days"),',
    '    keep_latest_tasks: cleanupFieldValue("keep_latest_tasks")',
    '  };',
    '}',
    'async function postCleanup(path, payload) {',
    '  const response = await fetch(path, {',
    '    method: "POST",',
    '    headers: { "content-type": "application/json", "x-garda-action-token": actionToken },',
    '    body: JSON.stringify(payload)',
    '  });',
    '  return response.json();',
    '}',
    'async function submitCleanupField(fieldKey, mode) {',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToApplySetting") + " \\"" + currentCleanupPayload.confirmation_phrase + "\\" " + t("typeToApplySettingTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  const result = await postCleanup("/api/cleanup-settings", { mode, settings: cleanupSettingsPatch(fieldKey), confirmation });',
    '  renderCleanupResult(result);',
    '  if (result.status === "executed") {',
    '    await refreshCleanupSettingsPayload();',
    '  }',
    '}',
    'async function runCleanup(mode) {',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToRunAction") + " \\"" + currentCleanupPayload.cleanup_confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  renderCleanupResult(await postCleanup("/api/cleanup-run", { ...cleanupRunSelectionFromInputs(), mode, confirmation }));',
    '}',
    'async function runTaskPurge(mode) {',
    '  const taskId = document.getElementById("cleanup-task-id").value;',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToRunAction") + " \\"" + currentCleanupPayload.task_purge_confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  renderCleanupResult(await postCleanup("/api/cleanup-task-purge", { task_id: taskId, mode, confirmation }));',
    '}',
    'function cleanupSaveButton(fieldKey, disabled) {',
    '  return "<div class=\\"setting-buttons\\"><button type=\\"button\\" data-cleanup-field=\\"" + safe(fieldKey) + "\\" data-cleanup-mode=\\"execute\\"" + (disabled ? " disabled" : "") + ">" + safe(t("save")) + "</button></div>";',
    '}',
    'function cleanupSettingRow(fieldKey, label, description, currentValue, controlHtml, disabled) {',
    '  return "<tr><td><strong>" + safe(label) + "</strong></td><td class=\\"description-cell\\">" + inlineText(description || "") + "</td><td><code class=\\"current-value\\">" + safe(String(currentValue)) + "</code></td><td><label class=\\"setting-control\\"><span>" + safe(t("newValue")) + "</span>" + controlHtml + "</label>" + cleanupSaveButton(fieldKey, disabled) + "</td></tr>";',
    '}',
    'function cleanupActionRow(label, description, controlHtml) {',
    '  return "<tr><td><strong>" + safe(label) + "</strong></td><td class=\\"description-cell\\">" + inlineText(description || "") + "</td><td><span class=\\"empty\\">—</span></td><td>" + controlHtml + "</td></tr>";',
    '}',
    'function cleanupRunPreviewLabel() {',
    '  return cleanupText("run_preview", "label", "Preview: do not delete");',
    '}',
    'function cleanupRunApplyLabel() {',
    '  return cleanupText("run_apply", "label", "Run cleanup");',
    '}',
    'function cleanupResultStatusLabel() {',
    '  return cleanupText("cleanup_result", "label", "Cleanup result");',
    '}',
    'function cleanupBooleanSelect(id, value, disabled) {',
    '  return "<select id=\\"" + safe(id) + "\\"" + (disabled ? " disabled" : "") + "><option value=\\"true\\"" + (value ? " selected" : "") + ">" + safe(cleanupText("value_true", "label", "true")) + "</option><option value=\\"false\\"" + (!value ? " selected" : "") + ">" + safe(cleanupText("value_false", "label", "false")) + "</option></select>";',
    '}',
    'function cleanupNumberInput(id, value, disabled) {',
    '  return "<input id=\\"" + safe(id) + "\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(value || 0)) + "\\"" + (disabled ? " disabled" : "") + ">";',
    '}',
    'function cleanupTextInput(id, placeholder, disabled) {',
    '  return "<input id=\\"" + safe(id) + "\\" type=\\"text\\" placeholder=\\"" + safe(placeholder) + "\\"" + (disabled ? " disabled" : "") + ">";',
    '}',
    'function wireCleanupSettingButtons(disabled) {',
    '  if (disabled) return;',
    '  for (const button of cleanupSettingsNode.querySelectorAll("button[data-cleanup-field]")) {',
    '    button.addEventListener("click", () => submitCleanupField(button.dataset.cleanupField, button.dataset.cleanupMode || "execute"));',
    '  }',
    '  document.getElementById("cleanup-run-preview").addEventListener("click", () => runCleanup("preview"));',
    '  document.getElementById("cleanup-run-apply").addEventListener("click", () => runCleanup("execute"));',
    '  document.getElementById("cleanup-task-purge-apply").addEventListener("click", () => runTaskPurge("execute"));',
    '}',
    'function renderCleanupSettings(payload) {',
    '  currentCleanupPayload = payload;',
    '  setPanelConfigPath(cleanupConfigPathNode, payload.config_path);',
    '  const settings = payload.settings || {};',
    '  const disabled = !payload.enabled;',
    '  const disabledNotice = disabled ? "<p class=\\"empty\\">" + safe(t("actionsDisabled")) + " <code>garda ui --actions</code> " + safe(t("actionsDisabledTail")) + "</p>" : "";',
    '  if (!currentCleanupResult) {',
    '    cleanupStatusNode.innerHTML = "";',
    '  }',
    '  cleanupSettingsNode.innerHTML = "<p class=\\"empty\\">" + safe(cleanupText("tab_intro", "description", "")) + "</p>" + disabledNotice',
    '    + "<div class=\\"workflow-table cleanup-settings-table\\"><table><thead><tr><th>" + safe(t("configSettingColumn")) + "</th><th>" + safe(t("descriptionColumn")) + "</th><th>" + safe(t("currentValueColumn")) + "</th><th>" + safe(t("changeColumn")) + "</th></tr></thead><tbody>"',
    '    + cleanupActionRow(cleanupText("manual_runtime_cleanup", "label", "Manual runtime cleanup"), cleanupText("manual_runtime_cleanup", "description", ""), "<div class=\\"setting-buttons\\"><button type=\\"button\\" id=\\"cleanup-run-preview\\"" + (disabled ? " disabled" : "") + ">" + safe(cleanupRunPreviewLabel()) + "</button><button type=\\"button\\" id=\\"cleanup-run-apply\\"" + (disabled ? " disabled" : "") + ">" + safe(cleanupRunApplyLabel()) + "</button></div>")',
    '    + cleanupActionRow(cleanupText("task_purge", "label", "Task purge"), cleanupText("task_purge", "description", ""), "<label class=\\"setting-control\\"><span>" + safe(cleanupText("task_id", "label", "Task ID")) + "</span>" + cleanupTextInput("cleanup-task-id", "T-123", disabled) + "</label><div class=\\"setting-buttons\\"><button type=\\"button\\" id=\\"cleanup-task-purge-apply\\"" + (disabled ? " disabled" : "") + ">" + safe(cleanupText("purge_task_button", "label", "Purge task")) + "</button></div>")',
    '    + cleanupSettingRow("daily_maintenance_enabled", cleanupText("daily_maintenance_enabled", "label", "Daily maintenance"), cleanupText("daily_maintenance_enabled", "description", ""), cleanupBooleanLabel(settings.daily_maintenance_enabled), cleanupBooleanSelect("cleanup-daily-enabled", settings.daily_maintenance_enabled, disabled), disabled)',
    '    + cleanupSettingRow("daily_maintenance_max_tasks_per_run", cleanupText("daily_maintenance_max_tasks_per_run", "label", "Max tasks per maintenance run"), cleanupText("daily_maintenance_max_tasks_per_run", "description", ""), settings.daily_maintenance_max_tasks_per_run, cleanupNumberInput("cleanup-max-tasks", settings.daily_maintenance_max_tasks_per_run, disabled), disabled)',
    '    + cleanupSettingRow("eligible_older_than_days", cleanupText("eligible_older_than_days", "label", "Minimum task age (days)"), cleanupText("eligible_older_than_days", "description", ""), settings.eligible_older_than_days, cleanupNumberInput("cleanup-older-than-days", settings.eligible_older_than_days, disabled), disabled)',
    '    + cleanupSettingRow("keep_latest_tasks", cleanupText("keep_latest_tasks", "label", "Keep newest tasks (count)"), cleanupText("keep_latest_tasks", "description", ""), settings.keep_latest_tasks, cleanupNumberInput("cleanup-keep-latest", settings.keep_latest_tasks, disabled), disabled)',
    '    + cleanupSettingRow("daily_maintenance_dry_run", cleanupText("daily_maintenance_dry_run", "label", "Daily maintenance dry-run"), cleanupText("daily_maintenance_dry_run", "description", ""), cleanupBooleanLabel(settings.daily_maintenance_dry_run), cleanupBooleanSelect("cleanup-daily-dry-run", settings.daily_maintenance_dry_run, disabled), disabled)',
    '    + cleanupSettingRow("purge_require_confirm", cleanupText("purge_require_confirm", "label", "Purge confirmation required"), cleanupText("purge_require_confirm", "description", ""), cleanupBooleanLabel(settings.purge_require_confirm), cleanupBooleanSelect("cleanup-purge-require-confirm", settings.purge_require_confirm, disabled), disabled)',
    '    + cleanupSettingRow("healthy_done_compact_after_days", cleanupText("healthy_done_compact_after_days", "label", "Compact healthy DONE after (days)"), cleanupText("healthy_done_compact_after_days", "description", ""), settings.healthy_done_compact_after_days, cleanupNumberInput("cleanup-healthy-compact-days", settings.healthy_done_compact_after_days, disabled), disabled)',
    '    + cleanupSettingRow("problem_tasks_compress_after_days", cleanupText("problem_tasks_compress_after_days", "label", "Compress problem tasks after (days)"), cleanupText("problem_tasks_compress_after_days", "description", ""), settings.problem_tasks_compress_after_days, cleanupNumberInput("cleanup-problem-compress-days", settings.problem_tasks_compress_after_days, disabled), disabled)',
    '    + "</tbody></table></div>";',
    '  wireCleanupSettingButtons(disabled);',
    '}',
    'async function refreshCleanupSettingsPayload() {',
    '  const response = await fetch("/api/cleanup-settings");',
    '  renderCleanupSettings(await response.json());',
    '}'
].join('\n');
