/** Browser-side dashboard script fragment (backups tab). */
export const UI_DASHBOARD_CLIENT_BACKUPS = [
    'const BACKUP_RESTORE_ACTION_PREFIX = "backup-restore:";',
    'const AUTO_BACKUP_SETTING_IDS = ["auto-backup-enabled", "auto-backup-interval-days", "auto-backup-keep-latest"];',
    'const backupsSettingsNode = document.getElementById("backups-settings");',
    'const backupsTableNode = document.getElementById("backups-table");',
    'const backupActionStatusNode = document.getElementById("backup-action-status");',
    'let currentBackupActionResult = null;',
    'let currentBackupSettingResult = null;',
    'function backupReasonLabel(reason) {',
    '  if (reason === "update") return t("backupReasonUpdate");',
    '  if (reason === "scheduled") return t("backupReasonScheduled");',
    '  return String(reason || "-");',
    '}',
    'function findBackupRestoreAction(backupId) {',
    '  const actionId = BACKUP_RESTORE_ACTION_PREFIX + backupId;',
    '  const actions = currentActionsPayload && currentActionsPayload.actions ? currentActionsPayload.actions : [];',
    '  return actions.find(item => item.id === actionId) || null;',
    '}',
    'function compactBackupResultText(result) {',
    '  if (result && result.status === "executed") return "OK";',
    '  const raw = String((result && (result.stderr || result.stdout || result.error || result.message)) || "");',
    '  if (!raw.trim()) return resultStatusText(result && result.status);',
    '  const normalized = raw.replace(/\\s+/g, " ").trim();',
    '  return resultStatusText(result && result.status) + ": " + (normalized.length > 240 ? normalized.slice(0, 240) + "..." : normalized);',
    '}',
    'function renderBackupActionResult(result) {',
    '  currentBackupSettingResult = null;',
    '  currentBackupActionResult = result;',
    '  const actionId = result.action_id || "";',
    '  const label = localizedField(actionTextPacks, actionId, "label", actionId || t("action"));',
    '  backupActionStatusNode.innerHTML = "<section class=\\"command-preview-panel\\">"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(t("action")) + "<code>" + safe(label) + "</code></span><span>" + safe(t("statusColumn")) + "<code>" + safe(compactBackupResultText(result)) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + "</section>";',
    '}',
    'function renderBackupSettingResult(result) {',
    '  currentBackupActionResult = null;',
    '  currentBackupSettingResult = result;',
    '  const label = localizedField(settingTextPacks, result.setting_id, "label", result.label || result.key || result.setting_id || t("setting"));',
    '  backupActionStatusNode.innerHTML = "<section class=\\"command-preview-panel\\">"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(t("setting")) + "<code>" + safe(label) + "</code></span><span>" + safe(t("statusColumn")) + "<code>" + safe(compactBackupResultText(result)) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + "</section>";',
    '}',
    'async function runBackupAction(actionId, mode, confirmation) {',
    '  const response = await fetch("/api/actions", {',
    '    method: "POST",',
    '    headers: { "content-type": "application/json", "x-garda-action-token": actionToken },',
    '    body: JSON.stringify({ action_id: actionId, mode, confirmation })',
    '  });',
    '  const result = await response.json();',
    '  renderBackupActionResult(result);',
    '  if (result && result.status === "executed") {',
    '    await refreshActionsPayload();',
    '    const reportResponse = await fetch("/api/report");',
    '    const report = await reportResponse.json();',
    '    currentReport = report;',
    '    renderBackups(report);',
    '  }',
    '}',
    'function wireBackupRestoreButtons(rootNode, actions) {',
    '  for (const button of rootNode.querySelectorAll("button[data-backup-action-id]")) {',
    '    button.addEventListener("click", () => {',
    '      const action = actions.find(item => item.id === button.dataset.backupActionId);',
    '      const mode = button.dataset.actionMode;',
    '      const confirmation = mode === "execute" && action && action.requires_confirmation',
    '        ? window.prompt(t("typeToRunAction") + " \\"" + action.confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '        : null;',
    '      if (mode === "execute" && action && action.requires_confirmation && confirmation === null) {',
    '        return;',
    '      }',
    '      runBackupAction(button.dataset.backupActionId, mode, confirmation);',
    '    });',
    '  }',
    '}',
    'function renderBackupsTable(tab) {',
    '  const rows = tab.rows || [];',
    '  const unavailable = tab.unavailable || [];',
    '  const actions = currentActionsPayload && currentActionsPayload.actions ? currentActionsPayload.actions : [];',
    '  if (rows.length === 0) {',
    '    backupsTableNode.innerHTML = "<h3>" + safe(t("backupsInventoryTitle")) + "</h3><p class=\\"empty\\">" + safe(t("backupsEmpty")) + "</p>"',
    '      + (unavailable.length > 0 ? "<ul>" + unavailable.map(item => "<li><code>" + safe(item.scope) + "</code>: " + safe(item.reason) + "</li>").join("") + "</ul>" : "");',
    '    return;',
    '  }',
    '  const disabled = !actionsEnabled;',
    '  backupsTableNode.innerHTML = "<h3>" + safe(t("backupsInventoryTitle")) + "</h3><p class=\\"meta\\">" + safe(t("backupsSnapshotsRoot")) + ": " + safe(tab.snapshots_root || "-") + " (" + safe(tab.snapshots_root_exists ? t("backupRootPresent") : t("backupRootMissing")) + ")</p>"',
    '    + "<div class=\\"workflow-table\\"><table><thead><tr><th>" + safe(t("backupIdColumn")) + "</th><th>" + safe(t("backupCreatedColumn")) + "</th><th>" + safe(t("backupSizeColumn")) + "</th><th>" + safe(t("backupReasonColumn")) + "</th><th>" + safe(t("backupStatusColumn")) + "</th><th>" + safe(t("backupRestoreColumn")) + "</th></tr></thead><tbody>"',
    '    + rows.map(row => {',
    '      const action = findBackupRestoreAction(row.id);',
    '      const restoreButtons = disabled',
    '        ? "<span class=\\"empty\\">" + safe(t("backupsActionsDisabled")) + " <code>garda ui --actions</code></span>"',
    '        : !action || !action.enabled',
    '        ? "<span class=\\"empty\\">" + safe((action && action.unavailable_reason) || t("backupRestoreUnavailable")) + "</span>"',
    '        : "<div class=\\"action-buttons\\"><button type=\\"button\\" data-backup-action-id=\\"" + safe(action.id) + "\\" data-action-mode=\\"execute\\">" + safe(t("restoreBackup")) + "</button></div>";',
    '      const healthLabel = row.health_message ? row.health + ": " + row.health_message : row.health;',
    '      return "<tr><td><code>" + safe(row.id) + "</code></td><td>" + safe(row.created_at) + "</td><td>" + safe(row.size_human) + "</td><td>" + safe(backupReasonLabel(row.reason)) + "</td><td>" + badge(healthLabel, "status") + "</td><td>" + restoreButtons + "</td></tr>";',
    '    }).join("")',
    '    + "</tbody></table></div>"',
    '    + (unavailable.length > 0 ? "<ul class=\\"list\\">" + unavailable.map(item => "<li><code>" + safe(item.scope) + "</code>: " + safe(item.reason) + "</li>").join("") + "</ul>" : "");',
    '  wireBackupRestoreButtons(backupsTableNode, actions);',
    '}',
    'async function refreshBackupsSettingsEditor() {',
    '  const response = await fetch("/api/settings");',
    '  const payload = await response.json();',
    '  currentSettingsPayload = payload;',
    '  if (currentReport) {',
    '    renderBackupsAutoBackupSettings(currentReport);',
    '  }',
    '}',
    'function renderBackupsAutoBackupSettings(report) {',
    '  const tab = report.backups_tab || {};',
    '  const auto = tab.auto_backup || { enabled: false, interval_days: 0, keep_latest: 10 };',
    '  if (!actionsEnabled) {',
    '    backupsSettingsNode.innerHTML = "<h3>" + safe(t("backupsAutoBackupTitle")) + "</h3><div class=\\"value-table\\"><table><tbody>"',
    '      + "<tr><th>" + safe(t("backupAutoEnabled")) + "</th><td><code>" + safe(String(auto.enabled)) + "</code></td></tr>"',
    '      + "<tr><th>" + safe(t("backupAutoIntervalDays")) + "</th><td><code>" + safe(String(auto.interval_days)) + "</code></td></tr>"',
    '      + "<tr><th>" + safe(t("backupAutoKeepLatest")) + "</th><td><code>" + safe(String(auto.keep_latest)) + "</code></td></tr>"',
    '      + "</tbody></table></div><p class=\\"empty\\">" + safe(t("backupsActionsDisabled")) + " <code>garda ui --actions</code></p>";',
    '    return;',
    '  }',
    '  const settings = (currentSettingsPayload && currentSettingsPayload.settings ? currentSettingsPayload.settings : []).filter(setting => AUTO_BACKUP_SETTING_IDS.includes(setting.id));',
    '  if (settings.length === 0) {',
    '    backupsSettingsNode.innerHTML = "<h3>" + safe(t("backupsAutoBackupTitle")) + "</h3><p class=\\"empty\\">" + safe(t("noEditableSettings")) + "</p>";',
    '    return;',
    '  }',
    '  function renderBackupSettingRow(setting) {',
    '    const label = localizedField(settingTextPacks, setting.id, "label", setting.label);',
    '    const description = localizedField(settingTextPacks, setting.id, "description", setting.description);',
    '    return "<tr><td><div class=\\"setting-title\\"><strong>" + safe(label) + "</strong><code>(" + safe(setting.key) + ")</code></div></td>"',
    '      + "<td class=\\"description-cell\\">" + inlineText(description) + "</td>"',
    '      + "<td><code class=\\"current-value\\">" + safe(isDurationMsSetting(setting) ? formatDurationMs(setting.current_value) : JSON.stringify(setting.current_value)) + "</code></td>"',
    '      + "<td><label class=\\"setting-control\\"><span>" + safe(t("newValue")) + "</span>" + renderSettingControl(setting, false, "backups") + "</label><div class=\\"setting-buttons\\"><button type=\\"button\\" data-setting-id=\\"" + safe(setting.id) + "\\" data-setting-control-scope=\\"backups\\" data-setting-mode=\\"execute\\">" + safe(t("save")) + "</button></div></td></tr>";',
    '  }',
    '  backupsSettingsNode.innerHTML = "<h3>" + safe(t("backupsAutoBackupTitle")) + "</h3><p class=\\"empty\\">" + safe(t("backupsAutoBackupHelp")) + "</p>"',
    '    + "<div class=\\"workflow-table\\"><table><thead><tr><th>" + safe(t("configSettingColumn")) + "</th><th>" + safe(t("descriptionColumn")) + "</th><th>" + safe(t("currentValueColumn")) + "</th><th>" + safe(t("changeColumn")) + "</th></tr></thead><tbody>"',
    '    + settings.map(setting => renderBackupSettingRow(setting)).join("")',
    '    + "</tbody></table></div>";',
    '  for (const button of backupsSettingsNode.querySelectorAll("button[data-setting-id]")) {',
    '    button.addEventListener("click", async () => {',
    '      const setting = settings.find(item => item.id === button.dataset.settingId);',
    '      const mode = button.dataset.settingMode;',
    '      const controlScope = button.dataset.settingControlScope || "backups";',
    '      const input = document.getElementById(settingControlId(button.dataset.settingId, controlScope));',
    '      const confirmation = mode === "execute" && setting',
    '        ? window.prompt(t("typeToApplySetting") + " \\"" + setting.confirmation_phrase + "\\" " + t("typeToApplySettingTail"))',
    '        : null;',
    '      if (mode === "execute" && confirmation === null) {',
    '        return;',
    '      }',
    '      await submitSetting(button.dataset.settingId, mode, settingSubmitValue(setting, input, controlScope), confirmation, renderBackupSettingResult);',
    '      await refreshBackupsSettingsEditor();',
    '      const reportResponse = await fetch("/api/report");',
    '      currentReport = await reportResponse.json();',
    '      renderBackups(currentReport);',
    '    });',
    '  }',
    '}',
    'function renderBackups(report) {',
    '  const tab = report.backups_tab || { rows: [], unavailable: [], auto_backup: { enabled: false, interval_days: 0, keep_latest: 10 } };',
    '  if (!currentBackupActionResult && !currentBackupSettingResult) {',
    '    backupActionStatusNode.innerHTML = "";',
    '  }',
    '  renderBackupsAutoBackupSettings(report);',
    '  renderBackupsTable(tab);',
    '}'
].join('\n');
