/** Browser-side dashboard script fragment (backups tab). */
export const UI_DASHBOARD_CLIENT_BACKUPS = [
    'const BACKUP_RESTORE_ACTION_PREFIX = "backup-restore:";',
    'const MANUAL_BACKUP_CREATE_ACTION_ID = "backup-create-manual";',
    'const AUTO_BACKUP_SETTING_IDS = ["auto-backup-enabled", "auto-backup-interval-days", "auto-backup-keep-latest"];',
    'const backupsSettingsNode = document.getElementById("backups-settings");',
    'const backupsTableNode = document.getElementById("backups-table");',
    'const backupActionStatusNode = document.getElementById("backup-action-status");',
    'let currentBackupActionResult = null;',
    'let currentBackupSettingResult = null;',
    'function backupText(id, field, fallback) {',
    '  return localizedField(backupsTabTextPacks, id, field, fallback);',
    '}',
    'function backupReasonLabel(reason) {',
    '  if (reason === "update") return backupText("reason_update", "label", "update");',
    '  if (reason === "scheduled") return backupText("reason_scheduled", "label", "scheduled");',
    '  if (reason === "manual") return backupText("reason_manual", "label", "manual");',
    '  return String(reason || "-");',
    '}',
    'function backupHealthLabel(health) {',
    '  if (health === "AVAILABLE") return backupText("health_available", "label", "Available");',
    '  if (health === "MISSING_RECORDS") return backupText("health_missing_records", "label", "Missing records");',
    '  if (health === "INVALID_RECORDS") return backupText("health_invalid_records", "label", "Invalid records");',
    '  return String(health || "-");',
    '}',
    'function findBackupRestoreAction(backupId) {',
    '  const actionId = BACKUP_RESTORE_ACTION_PREFIX + backupId;',
    '  const actions = currentActionsPayload && currentActionsPayload.actions ? currentActionsPayload.actions : [];',
    '  return actions.find(item => item.id === actionId) || null;',
    '}',
    'function findManualBackupCreateAction() {',
    '  const actions = currentActionsPayload && currentActionsPayload.actions ? currentActionsPayload.actions : [];',
    '  return actions.find(item => item.id === MANUAL_BACKUP_CREATE_ACTION_ID) || null;',
    '}',
    'function compactBackupResultText(result) {',
    '  const exitCode = result && typeof result.exit_code === "number" ? result.exit_code : null;',
    '  const succeeded = result && result.status === "executed" && (result.http_ok === true || exitCode === 0) && (exitCode === null || exitCode === 0);',
    '  if (succeeded && result.action_id === MANUAL_BACKUP_CREATE_ACTION_ID) {',
    '    const summary = compactManualBackupCreateOutput(result.stdout);',
    '    return summary ? "OK: " + summary : "OK";',
    '  }',
    '  if (succeeded) return "OK";',
    '  const raw = String((result && (result.stderr || result.stdout || result.error || result.message)) || "");',
    '  if (!raw.trim()) return resultStatusText(result && result.status);',
    '  const normalized = raw.replace(/\\s+/g, " ").trim();',
    '  return resultStatusText(result && result.status) + ": " + (normalized.length > 240 ? normalized.slice(0, 240) + "..." : normalized);',
    '}',
    'function compactManualBackupCreateOutput(stdout) {',
    '  const allowed = new Set(["Status", "BackupPath", "RetentionResult", "RetentionKeepLatest", "RetentionRemovedCount", "RetentionSkippedCount", "RetentionErrorCount", "RetentionTotalFreedBytes"]);',
    '  const labels = { RetentionKeepLatest: "Keep", RetentionRemovedCount: "Removed", RetentionSkippedCount: "Skipped", RetentionErrorCount: "Errors", RetentionTotalFreedBytes: "FreedBytes" };',
    '  const parts = [];',
    '  for (const line of String(stdout || "").split(/\\r?\\n/)) {',
    '    const match = line.match(/^([A-Za-z][A-Za-z0-9]*):\\s*(.*)$/);',
    '    if (!match || !allowed.has(match[1])) continue;',
    '    const label = labels[match[1]] || match[1];',
    '    const value = match[2].trim();',
    '    if (value) parts.push(label + "=" + value);',
    '  }',
    '  const text = parts.join("; ");',
    '  return text.length > 360 ? text.slice(0, 360) + "..." : text;',
    '}',
    'function renderBackupActionResult(result) {',
    '  currentBackupSettingResult = null;',
    '  currentBackupActionResult = result;',
    '  const actionId = result.action_id || "";',
    '  const label = localizedField(actionTextPacks, actionId, "label", actionId || t("action"));',
    '  backupActionStatusNode.innerHTML = "<section class=\\"command-preview-panel\\">"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(t("action")) + "<code>" + safe(label) + "</code></span><span>" + safe(t("statusColumn")) + "<code>" + safe(compactBackupResultText(result)) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + "</section>";',
    '  focusVisibleActionResult(backupActionStatusNode);',
    '}',
    'function renderBackupSettingResult(result) {',
    '  currentBackupActionResult = null;',
    '  currentBackupSettingResult = result;',
    '  const label = localizedField(settingTextPacks, result.setting_id, "label", result.label || result.key || result.setting_id || t("setting"));',
    '  backupActionStatusNode.innerHTML = "<section class=\\"command-preview-panel\\">"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(t("setting")) + "<code>" + safe(label) + "</code></span><span>" + safe(t("statusColumn")) + "<code>" + safe(compactBackupResultText(result)) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + "</section>";',
    '  focusVisibleActionResult(backupActionStatusNode);',
    '}',
    'async function runBackupAction(actionId, mode, confirmation) {',
    '  const response = await fetch("/api/actions", {',
    '    method: "POST",',
    '    headers: { "content-type": "application/json", "x-garda-action-token": actionToken },',
    '    body: JSON.stringify({ action_id: actionId, mode, confirmation })',
    '  });',
    '  const result = await response.json();',
    '  result.http_ok = response.ok;',
    '  renderBackupActionResult(result);',
    '  const exitCode = result && typeof result.exit_code === "number" ? result.exit_code : null;',
    '  if (response.ok && result && result.status === "executed" && (exitCode === null || exitCode === 0)) {',
    '    await refreshActionsPayload();',
    '    const reportResponse = await fetch("/api/report");',
    '    const report = await reportResponse.json();',
    '    currentReport = report;',
    '    renderBackups(report);',
    '  }',
    '}',
    'function wireBackupRestoreButtons(rootNode, actions) {',
    '  for (const button of rootNode.querySelectorAll("button[data-backup-action-id]")) {',
    '    button.addEventListener("click", () => {',
    '      const action = actions.find(item => item.id === button.dataset.backupActionId);',
    '      const mode = button.dataset.actionMode;',
    '      const confirmation = mode === "execute" && action && action.requires_confirmation',
    '        ? window.prompt(t("typeToRunAction") + " \\"" + action.confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '        : null;',
    '      if (mode === "execute" && action && action.requires_confirmation && confirmation === null) {',
    '        return;',
    '      }',
    '      runBackupAction(button.dataset.backupActionId, mode, confirmation);',
    '    });',
    '  }',
    '}',
    'function renderManualBackupCreatePanel() {',
    '  const action = findManualBackupCreateAction();',
    '  const buttonHtml = !actionsEnabled',
    '    ? "<p class=\\"empty\\">" + safe(backupText("actions_disabled", "label", "Controlled actions are disabled.")) + " <code>garda ui --actions</code></p>"',
    '    : !action || !action.enabled',
    '    ? "<p class=\\"empty\\">" + safe((action && action.unavailable_reason) || backupText("manual_create_unavailable", "label", "Manual backup creation is unavailable.")) + "</p>"',
    '    : "<div class=\\"action-buttons\\"><button type=\\"button\\" data-backup-action-id=\\"" + safe(action.id) + "\\" data-action-mode=\\"execute\\">" + safe(backupText("manual_create_button", "label", "Create backup")) + "</button></div>";',
    '  return "<section class=\\"command-preview-panel\\"><h3>" + safe(backupText("manual_create_title", "label", "Manual backup")) + "</h3><p class=\\"empty\\">" + safe(backupText("manual_create_help", "description", "Create a rollback backup snapshot of the current workspace state through the guarded backup backend.")) + "</p>" + buttonHtml + "</section>";',
    '}',
    'function renderBackupsTable(tab) {',
    '  const rows = tab.rows || [];',
    '  const unavailable = tab.unavailable || [];',
    '  const actions = currentActionsPayload && currentActionsPayload.actions ? currentActionsPayload.actions : [];',
    '  const manualPanel = renderManualBackupCreatePanel();',
    '  if (rows.length === 0) {',
    '    backupsTableNode.innerHTML = manualPanel + "<h3>" + safe(backupText("inventory_title", "label", "Backup list")) + "</h3><p class=\\"empty\\">" + safe(backupText("empty", "label", "No backups in list.")) + "</p>"',
    '      + (unavailable.length > 0 ? "<ul>" + unavailable.map(item => "<li><code>" + safe(item.scope) + "</code>: " + safe(item.reason) + "</li>").join("") + "</ul>" : "");',
    '    wireBackupRestoreButtons(backupsTableNode, actions);',
    '    return;',
    '  }',
    '  const disabled = !actionsEnabled;',
    '  backupsTableNode.innerHTML = manualPanel + "<h3>" + safe(backupText("inventory_title", "label", "Backup list")) + "</h3><p class=\\"meta\\">" + safe(backupText("snapshots_root", "label", "Snapshots root")) + ": " + safe(tab.snapshots_root || "-") + " (" + safe(tab.snapshots_root_exists ? backupText("root_present", "label", "present") : backupText("root_missing", "label", "missing")) + ")</p>"',
    '    + "<div class=\\"workflow-table\\"><table><thead><tr><th>" + safe(backupText("id_column", "label", "ID")) + "</th><th>" + safe(backupText("created_column", "label", "Created")) + "</th><th>" + safe(backupText("size_column", "label", "Size")) + "</th><th>" + safe(backupText("reason_column", "label", "Reason")) + "</th><th>" + safe(backupText("status_column", "label", "Health")) + "</th><th>" + safe(backupText("restore_column", "label", "Restore")) + "</th></tr></thead><tbody>"',
    '    + rows.map(row => {',
    '      const action = findBackupRestoreAction(row.id);',
    '      const restoreButtons = disabled',
    '        ? "<span class=\\"empty\\">" + safe(backupText("actions_disabled", "label", "Controlled actions are disabled.")) + " <code>garda ui --actions</code></span>"',
    '        : !action || !action.enabled',
    '        ? "<span class=\\"empty\\">" + safe((action && action.unavailable_reason) || backupText("restore_unavailable", "label", "Restore unavailable for this backup.")) + "</span>"',
    '        : "<div class=\\"action-buttons\\"><button type=\\"button\\" data-backup-action-id=\\"" + safe(action.id) + "\\" data-action-mode=\\"execute\\">" + safe(backupText("restore_backup", "label", "Restore backup")) + "</button></div>";',
    '      const healthLabel = row.health_message ? backupHealthLabel(row.health) + ": " + row.health_message : backupHealthLabel(row.health);',
    '      return "<tr><td><code>" + safe(row.id) + "</code></td><td>" + safe(row.created_at) + "</td><td>" + safe(row.size_human) + "</td><td>" + safe(backupReasonLabel(row.reason)) + "</td><td>" + badge(healthLabel, "status") + "</td><td>" + restoreButtons + "</td></tr>";',
    '    }).join("")',
    '    + "</tbody></table></div>"',
    '    + (unavailable.length > 0 ? "<ul class=\\"list\\">" + unavailable.map(item => "<li><code>" + safe(item.scope) + "</code>: " + safe(item.reason) + "</li>").join("") + "</ul>" : "");',
    '  wireBackupRestoreButtons(backupsTableNode, actions);',
    '}',
    'async function refreshBackupsSettingsEditor() {',
    '  const response = await fetch("/api/settings");',
    '  const payload = await response.json();',
    '  currentSettingsPayload = payload;',
    '  if (currentReport) {',
    '    renderBackupsAutoBackupSettings(currentReport);',
    '  }',
    '}',
    'function renderBackupsAutoBackupSettings(report) {',
    '  const tab = report.backups_tab || {};',
    '  const auto = tab.auto_backup || { enabled: false, interval_days: 0, keep_latest: 10 };',
    '  if (!actionsEnabled) {',
    '    backupsSettingsNode.innerHTML = "<h3>" + safe(backupText("auto_backup_title", "label", "Auto-backup")) + "</h3><div class=\\"value-table\\"><table><tbody>"',
    '      + "<tr><th>" + safe(backupText("auto_enabled", "label", "Enabled")) + "</th><td><code>" + safe(String(auto.enabled)) + "</code></td></tr>"',
    '      + "<tr><th>" + safe(backupText("auto_interval_days", "label", "Interval (days)")) + "</th><td><code>" + safe(String(auto.interval_days)) + "</code></td></tr>"',
    '      + "<tr><th>" + safe(backupText("auto_keep_latest", "label", "Keep latest")) + "</th><td><code>" + safe(String(auto.keep_latest)) + "</code></td></tr>"',
    '      + "</tbody></table></div><p class=\\"empty\\">" + safe(backupText("actions_disabled", "label", "Controlled actions are disabled.")) + " <code>garda ui --actions</code></p>";',
    '    return;',
    '  }',
    '  const settings = (currentSettingsPayload && currentSettingsPayload.settings ? currentSettingsPayload.settings : []).filter(setting => AUTO_BACKUP_SETTING_IDS.includes(setting.id));',
    '  if (settings.length === 0) {',
    '    backupsSettingsNode.innerHTML = "<h3>" + safe(backupText("auto_backup_title", "label", "Auto-backup")) + "</h3><p class=\\"empty\\">" + safe(t("noEditableSettings")) + "</p>";',
    '    return;',
    '  }',
    '  function renderBackupSettingRow(setting) {',
    '    const label = localizedField(settingTextPacks, setting.id, "label", setting.label);',
    '    const description = localizedField(settingTextPacks, setting.id, "description", setting.description);',
    '    return "<tr><td><div class=\\"setting-title\\"><strong>" + safe(label) + "</strong><code>(" + safe(setting.key) + ")</code></div></td>"',
    '      + "<td class=\\"description-cell\\">" + inlineText(description) + "</td>"',
    '      + "<td><code class=\\"current-value\\">" + safe(isDurationMsSetting(setting) ? formatDurationMs(setting.current_value) : JSON.stringify(setting.current_value)) + "</code></td>"',
    '      + "<td><label class=\\"setting-control\\"><span>" + safe(t("newValue")) + "</span>" + renderSettingControl(setting, false, "backups") + "</label><div class=\\"setting-buttons\\"><button type=\\"button\\" data-setting-id=\\"" + safe(setting.id) + "\\" data-setting-control-scope=\\"backups\\" data-setting-mode=\\"execute\\">" + safe(t("save")) + "</button></div></td></tr>";',
    '  }',
    '  backupsSettingsNode.innerHTML = "<p class=\\"empty\\">" + safe(backupText("tab_intro", "description", "")) + "</p><h3>" + safe(backupText("auto_backup_title", "label", "Auto-backup")) + "</h3><p class=\\"empty\\">" + safe(backupText("auto_backup_help", "description", "")) + "</p>"',
    '    + "<div class=\\"workflow-table\\"><table><thead><tr><th>" + safe(t("configSettingColumn")) + "</th><th>" + safe(t("descriptionColumn")) + "</th><th>" + safe(t("currentValueColumn")) + "</th><th>" + safe(t("changeColumn")) + "</th></tr></thead><tbody>"',
    '    + settings.map(setting => renderBackupSettingRow(setting)).join("")',
    '    + "</tbody></table></div>";',
    '  for (const button of backupsSettingsNode.querySelectorAll("button[data-setting-id]")) {',
    '    button.addEventListener("click", async () => {',
    '      const setting = settings.find(item => item.id === button.dataset.settingId);',
    '      const mode = button.dataset.settingMode;',
    '      const controlScope = button.dataset.settingControlScope || "backups";',
    '      const input = document.getElementById(settingControlId(button.dataset.settingId, controlScope));',
    '      const confirmation = mode === "execute" && setting',
    '        ? window.prompt(t("typeToApplySetting") + " \\"" + setting.confirmation_phrase + "\\" " + t("typeToApplySettingTail"))',
    '        : null;',
    '      if (mode === "execute" && confirmation === null) {',
    '        return;',
    '      }',
    '      await submitSetting(button.dataset.settingId, mode, settingSubmitValue(setting, input, controlScope), confirmation, renderBackupSettingResult);',
    '      await refreshBackupsSettingsEditor();',
    '      const reportResponse = await fetch("/api/report");',
    '      currentReport = await reportResponse.json();',
    '      renderBackups(currentReport);',
    '    });',
    '  }',
    '}',
    'function renderBackups(report) {',
    '  const tab = report.backups_tab || { rows: [], unavailable: [], auto_backup: { enabled: false, interval_days: 0, keep_latest: 10 } };',
    '  setPanelConfigPath(backupsConfigPathNode, [',
    '    tab.workflow_config_path,',
    '    tab.snapshots_root',
    '  ]);',
    '  if (!currentBackupActionResult && !currentBackupSettingResult) {',
    '    backupActionStatusNode.innerHTML = "";',
    '  }',
    '  renderBackupsAutoBackupSettings(report);',
    '  renderBackupsTable(tab);',
    '}'
].join('\n');
