/** Browser-side dashboard script fragment for narrow chrome/action polish overrides. */
export const UI_DASHBOARD_CLIENT_POLISH = [
    'function renderSession(session) {',
    '  currentSession = session;',
    '  if (!session || session.state === "unavailable") {',
    '    sessionSummaryNode.innerHTML = "<span class=\\"session-stopping\\">" + safe(t("serverUnavailable")) + " <code>garda ui</code> " + safe(t("serverUnavailableTail")) + "</span>";',
    '    sessionCountdownNode.max = "1";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  if (!session.enabled) {',
    '    sessionSummaryNode.innerHTML = safe(t("idleShutdownDisabled"));',
    '    sessionCountdownNode.max = "1";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  const warningSeconds = Number(session.seconds_until_warning || 0);',
    '  const shutdownSeconds = Number(session.seconds_until_shutdown || 0);',
    '  const totalShutdownSeconds = session.state === "active" ? warningSeconds : shutdownSeconds;',
    '  sessionCountdownNode.max = String(Math.max(1, Number(session.warning_seconds || 1)));',
    '  sessionCountdownNode.value = String(session.state === "warning" ? Math.max(0, shutdownSeconds) : Number(session.warning_seconds || 1));',
    '  if (session.state === "stopping") {',
    '    sessionSummaryNode.innerHTML = "<span class=\\"session-stopping\\">" + safe(t("stopping")) + "</span>";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  if (session.state === "warning") {',
    '    sessionSummaryNode.innerHTML = "<strong class=\\"session-warning\\">" + safe(t("shutdownIn")) + ":</strong> " + safe(formatSeconds(totalShutdownSeconds));',
    '    return;',
    '  }',
    '  sessionSummaryNode.innerHTML = "<strong>" + safe(t("shutdownIn")) + ":</strong> " + safe(formatSeconds(totalShutdownSeconds));',
    '}',
    'async function refreshSession() {',
    '  try {',
    '    const response = await fetch("/api/session");',
    '    renderSession(await response.json());',
    '  } catch (error) {',
    '    renderSession({ enabled: true, state: "unavailable" });',
    '    if (sessionPollTimer) {',
    '      clearInterval(sessionPollTimer);',
    '      sessionPollTimer = null;',
    '    }',
    '  }',
    '}',
    'function isBackupRestoreAction(action) {',
    '  return action && ((action.category || "") === "Backups" || String(action.id || "").startsWith(BACKUP_RESTORE_ACTION_PREFIX));',
    '}',
    'function renderActions(payload) {',
    '  currentActionsPayload = payload;',
    '  renderGardaSwitch(payload);',
    '  if (currentReport) {',
    '    renderBackups(currentReport);',
    '  }',
    '}',
    'function instructionLinks(id) {',
    '  const links = [];',
    '  if (id === "task-inspection" || id === "task-execution") {',
    '    links.push(["tasks-tab", t("tasksTab")]);',
    '  }',
    '  if (id === "workflow-configuration" || id === "review-execution-modes" || id === "workflow-guards") {',
    '    links.push(["workflow-tab", t("workflowTab")]);',
    '  }',
    '  if (id === "workspace-actions") {',
    '    links.push(["backups-tab", t("backupsTab")]);',
    '    links.push(["cleanup-settings-tab", t("cleanupSettingsTab")]);',
    '  }',
    '  if (id === "backups") {',
    '    links.push(["backups-tab", t("backupsTab")]);',
    '  }',
    '  if (id === "init-settings") {',
    '    links.push(["init-settings-tab", t("initSettingsTab")]);',
    '  }',
    '  if (id === "project-memory") {',
    '    links.push(["project-memory-tab", t("projectMemoryTab")]);',
    '  }',
    '  if (links.length === 0) {',
    '    return "";',
    '  }',
    '  return "<div class=\\"instruction-links\\">" + links.map(([tabId, label]) => "<button type=\\"button\\" data-instruction-tab=\\"" + safe(tabId) + "\\">" + safe(label) + "</button>").join("") + "</div>";',
    '}'
].join('\n');
