/** Browser-side dashboard script fragment for narrow chrome/action polish overrides. */
export const UI_DASHBOARD_CLIENT_POLISH = [
    'function renderSession(session) {',
    '  currentSession = session;',
    '  if (!session || session.state === "unavailable") {',
    '    sessionSummaryNode.innerHTML = "<span class=\\"session-stopping\\">" + safe(t("serverUnavailable")) + " <code>garda ui</code> " + safe(t("serverUnavailableTail")) + "</span>";',
    '    sessionCountdownNode.max = "1";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  if (!session.enabled) {',
    '    sessionSummaryNode.innerHTML = safe(t("idleShutdownDisabled"));',
    '    sessionCountdownNode.max = "1";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  const warningSeconds = Number(session.seconds_until_warning || 0);',
    '  const shutdownSeconds = Number(session.seconds_until_shutdown || 0);',
    '  const totalShutdownSeconds = session.state === "active" ? warningSeconds : shutdownSeconds;',
    '  sessionCountdownNode.max = String(Math.max(1, Number(session.warning_seconds || 1)));',
    '  sessionCountdownNode.value = String(session.state === "warning" ? Math.max(0, shutdownSeconds) : Number(session.warning_seconds || 1));',
    '  if (session.state === "stopping") {',
    '    sessionSummaryNode.innerHTML = "<span class=\\"session-stopping\\">" + safe(t("stopping")) + "</span>";',
    '    sessionCountdownNode.value = "0";',
    '    return;',
    '  }',
    '  if (session.state === "warning") {',
    '    sessionSummaryNode.innerHTML = "<strong class=\\"session-warning\\">" + safe(t("shutdownIn")) + ":</strong> " + safe(formatSeconds(totalShutdownSeconds));',
    '    return;',
    '  }',
    '  sessionSummaryNode.innerHTML = "<strong>" + safe(t("shutdownIn")) + ":</strong> " + safe(formatSeconds(totalShutdownSeconds));',
    '}',
    'async function refreshSession() {',
    '  try {',
    '    const response = await fetch("/api/session");',
    '    renderSession(await response.json());',
    '  } catch (error) {',
    '    renderSession({ enabled: true, state: "unavailable" });',
    '    if (sessionPollTimer) {',
    '      clearInterval(sessionPollTimer);',
    '      sessionPollTimer = null;',
    '    }',
    '  }',
    '}',
    'function isBackupRestoreAction(action) {',
    '  return action && ((action.category || "") === "Backups" || String(action.id || "").startsWith(BACKUP_RESTORE_ACTION_PREFIX));',
    '}',
    'function renderActions(payload) {',
    '  currentActionsPayload = payload;',
    '  renderGardaSwitch(payload);',
    '  if (!payload.enabled) {',
    '    actionsNode.innerHTML = "<p class=\\"empty\\">" + safe(t("actionsDisabled")) + " <code>garda ui --actions</code> " + safe(t("actionsDisabledTail")) + "</p><p class=\\"empty\\">" + safe(t("actionsTaskMoved")) + "</p>";',
    '    return;',
    '  }',
    '  if (!currentActionResult) {',
    '    actionStatusNode.innerHTML = "<section class=\\"command-preview-panel\\"><h3>" + safe(t("workflowCommandPreview")) + "</h3><p class=\\"empty\\">" + safe(t("actionsPreviewHelp")) + "</p></section>";',
    '  }',
    '  const visibleActions = (payload.actions || []).filter(action => !isBackupRestoreAction(action));',
    '  const categories = uniqueSorted(visibleActions.map(action => action.category || "Workspace"));',
    '  actionsNode.innerHTML = categories.length === 0',
    '    ? "<p class=\\"empty\\">" + safe(t("actionsTaskMoved")) + "</p>"',
    '    : categories.map(category => {',
    '      const actions = visibleActions.filter(action => (action.category || "Workspace") === category);',
    '      return "<section class=\\"action-section\\"><h3>" + safe(actionCategoryLabel(category)) + "</h3><div class=\\"action-table\\"><table><thead><tr><th>" + safe(t("action")) + "</th><th>" + safe(t("descriptionColumn")) + "</th><th>" + safe(t("actionEffectColumn")) + "</th><th>" + safe(t("commandColumn")) + "</th><th>" + safe(t("actionRunColumn")) + "</th></tr></thead><tbody>"',
    '        + actions.map(action => "<tr><td><strong>" + safe(actionLabel(action)) + "</strong></td><td class=\\"description-cell\\">" + inlineText(actionDescription(action)) + "</td><td><span class=\\"action-kind" + (action.mutates ? " mutates" : "") + "\\">" + safe(actionChangeLabel(action)) + "</span></td><td class=\\"command-cell\\"><code>" + safe(action.command) + "</code></td><td><div class=\\"action-buttons\\"><button type=\\"button\\" data-action-id=\\"" + safe(action.id) + "\\" data-action-mode=\\"preview\\">" + safe(t("previewCommand")) + "</button><button type=\\"button\\" data-action-id=\\"" + safe(action.id) + "\\" data-action-mode=\\"execute\\">" + safe(t("run")) + "</button></div></td></tr>").join("")',
    '        + "</tbody></table></div></section>";',
    '    }).join("");',
    '  wireActionButtons(actionsNode, visibleActions);',
    '  if (currentReport) {',
    '    renderBackups(currentReport);',
    '  }',
    '}',
    'function instructionLinks(id) {',
    '  const links = [];',
    '  if (id === "task-inspection" || id === "task-execution") {',
    '    links.push(["tasks-tab", t("tasksTab")]);',
    '  }',
    '  if (id === "workflow-configuration" || id === "review-execution-modes" || id === "workflow-guards") {',
    '    links.push(["workflow-tab", t("workflowTab")]);',
    '  }',
    '  if (id === "workspace-actions") {',
    '    links.push(["actions-tab", t("actionsTab")]);',
    '    links.push(["backups-tab", t("backupsTab")]);',
    '  }',
    '  if (id === "backups") {',
    '    links.push(["backups-tab", t("backupsTab")]);',
    '  }',
    '  if (id === "init-settings") {',
    '    links.push(["init-settings-tab", t("initSettingsTab")]);',
    '  }',
    '  if (id === "project-memory") {',
    '    links.push(["project-memory-tab", t("projectMemoryTab")]);',
    '  }',
    '  if (links.length === 0) {',
    '    return "";',
    '  }',
    '  return "<div class=\\"instruction-links\\">" + links.map(([tabId, label]) => "<button type=\\"button\\" data-instruction-tab=\\"" + safe(tabId) + "\\">" + safe(label) + "</button>").join("") + "</div>";',
    '}'
].join('\n');
