/** Browser-side dashboard script fragment (cleanup settings tab). */
export const UI_DASHBOARD_CLIENT_CLEANUP = [
    'let currentCleanupPayload = null;',
    'let currentCleanupResult = null;',
    'function renderCleanupResult(result) {',
    '  currentCleanupResult = result;',
    '  const label = result.action_id || t("cleanupSettingsTab");',
    '  cleanupStatusNode.innerHTML = "<section class=\\"command-preview-panel\\"><h3>" + safe(t("workflowCommandPreview")) + "</h3>"',
    '    + "<div class=\\"command-preview-main\\"><strong>" + safe(label) + "</strong><br><code>" + safe(result.command || "-") + "</code></div>"',
    '    + "<div class=\\"command-preview-meta\\"><span>" + safe(t("statusColumn")) + "<code>" + safe(resultStatusText(result.status)) + "</code></span></div>"',
    '    + (result.audit_path ? "<p><strong>" + safe(t("audit")) + ":</strong> <code>" + safe(result.audit_path) + "</code></p>" : "")',
    '    + outputBlock("stdout", result.stdout)',
    '    + outputBlock("stderr", result.stderr)',
    '    + (result.error ? "<p class=\\"error\\">" + safe(result.error) + "</p>" : "")',
    '    + "</section>";',
    '}',
    'function cleanupSettingsFromInputs() {',
    '  return {',
    '    daily_maintenance_enabled: document.getElementById("cleanup-daily-enabled").checked,',
    '    daily_maintenance_max_tasks_per_run: document.getElementById("cleanup-max-tasks").value,',
    '    eligible_older_than_days: document.getElementById("cleanup-older-than-days").value,',
    '    keep_latest_tasks: document.getElementById("cleanup-keep-latest").value,',
    '    daily_maintenance_dry_run: document.getElementById("cleanup-daily-dry-run").checked',
    '  };',
    '}',
    'function cleanupSelectionFromInputs() {',
    '  return {',
    '    eligible_older_than_days: document.getElementById("cleanup-run-older-than-days").value,',
    '    keep_latest_tasks: document.getElementById("cleanup-run-keep-latest").value',
    '  };',
    '}',
    'async function postCleanup(path, payload) {',
    '  const response = await fetch(path, {',
    '    method: "POST",',
    '    headers: { "content-type": "application/json", "x-garda-action-token": actionToken },',
    '    body: JSON.stringify(payload)',
    '  });',
    '  return response.json();',
    '}',
    'async function submitCleanupSettings(mode) {',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToApplySetting") + " \\"" + currentCleanupPayload.confirmation_phrase + "\\" " + t("typeToApplySettingTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  const result = await postCleanup("/api/cleanup-settings", { mode, settings: cleanupSettingsFromInputs(), confirmation });',
    '  renderCleanupResult(result);',
    '  if (result.status === "executed") {',
    '    await refreshCleanupSettingsPayload();',
    '  }',
    '}',
    'async function runCleanup(mode) {',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToRunAction") + " \\"" + currentCleanupPayload.cleanup_confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  renderCleanupResult(await postCleanup("/api/cleanup-run", { ...cleanupSelectionFromInputs(), mode, confirmation }));',
    '}',
    'async function runTaskPurge(mode) {',
    '  const taskId = document.getElementById("cleanup-task-id").value;',
    '  const confirmation = mode === "execute"',
    '    ? window.prompt(t("typeToRunAction") + " \\"" + currentCleanupPayload.task_purge_confirmation_phrase + "\\" " + t("typeToRunActionTail"))',
    '    : null;',
    '  if (mode === "execute" && confirmation === null) return;',
    '  renderCleanupResult(await postCleanup("/api/cleanup-task-purge", { task_id: taskId, mode, confirmation }));',
    '}',
    'function cleanupValueRow(label, value) {',
    '  return "<tr><th>" + safe(label) + "</th><td><code>" + safe(String(value)) + "</code></td></tr>";',
    '}',
    'function renderCleanupSettings(payload) {',
    '  currentCleanupPayload = payload;',
    '  const settings = payload.settings || {};',
    '  const disabled = !payload.enabled;',
    '  if (!currentCleanupResult) {',
    '    cleanupStatusNode.innerHTML = "<section class=\\"command-preview-panel\\"><h3>" + safe(t("workflowCommandPreview")) + "</h3><p class=\\"empty\\">" + safe(t("cleanupPreviewHelp")) + "</p></section>";',
    '  }',
    '  cleanupSettingsNode.innerHTML = "<div class=\\"cleanup-grid\\">"',
    '    + "<section class=\\"cleanup-section\\"><h3>" + safe(t("cleanupEffectivePolicyTitle")) + "</h3><p class=\\"empty\\">" + safe(t("cleanupEffectivePolicyHelp")) + "</p><div class=\\"value-table\\"><table><tbody>"',
    '    + cleanupValueRow(t("cleanupPolicyPath"), payload.config_path || "-")',
    '    + cleanupValueRow(t("cleanupDailyEnabled"), settings.daily_maintenance_enabled)',
    '    + cleanupValueRow(t("cleanupDailyDryRun"), settings.daily_maintenance_dry_run)',
    '    + cleanupValueRow(t("cleanupOlderThanDays"), settings.eligible_older_than_days)',
    '    + cleanupValueRow(t("cleanupKeepLatestTasks"), settings.keep_latest_tasks)',
    '    + cleanupValueRow(t("cleanupPurgeRequireConfirm"), settings.purge_require_confirm)',
    '    + cleanupValueRow(t("cleanupHealthyDoneCompactDays"), settings.healthy_done_compact_after_days)',
    '    + cleanupValueRow(t("cleanupProblemCompressDays"), settings.problem_tasks_compress_after_days)',
    '    + "</tbody></table></div></section>"',
    '    + "<section class=\\"cleanup-section\\"><h3>" + safe(t("cleanupEditSettingsTitle")) + "</h3><p class=\\"empty\\">" + safe(disabled ? t("actionsDisabled") : t("cleanupEditSettingsHelp")) + (disabled ? " <code>garda ui --actions</code>" : "") + "</p>"',
    '    + "<div class=\\"cleanup-form\\">"',
    '    + "<label><input id=\\"cleanup-daily-enabled\\" type=\\"checkbox\\"" + (settings.daily_maintenance_enabled ? " checked" : "") + (disabled ? " disabled" : "") + "> " + safe(t("cleanupDailyEnabled")) + "</label>"',
    '    + "<label><span>" + safe(t("cleanupMaxTasksPerRun")) + "</span><input id=\\"cleanup-max-tasks\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(settings.daily_maintenance_max_tasks_per_run || 0)) + "\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<label><span>" + safe(t("cleanupOlderThanDays")) + "</span><input id=\\"cleanup-older-than-days\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(settings.eligible_older_than_days || 0)) + "\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<label><span>" + safe(t("cleanupKeepLatestTasks")) + "</span><input id=\\"cleanup-keep-latest\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(settings.keep_latest_tasks || 0)) + "\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<label><input id=\\"cleanup-daily-dry-run\\" type=\\"checkbox\\"" + (settings.daily_maintenance_dry_run ? " checked" : "") + (disabled ? " disabled" : "") + "> " + safe(t("cleanupDailyDryRun")) + "</label>"',
    '    + "<div class=\\"action-buttons\\"><button type=\\"button\\" id=\\"cleanup-settings-preview\\"" + (disabled ? " disabled" : "") + ">" + safe(t("previewCommand")) + "</button><button type=\\"button\\" id=\\"cleanup-settings-save\\"" + (disabled ? " disabled" : "") + ">" + safe(t("save")) + "</button></div>"',
    '    + "</div></section>"',
    '    + "<section class=\\"cleanup-section\\"><h3>" + safe(t("cleanupRunTitle")) + "</h3><p class=\\"empty\\">" + safe(t("cleanupRunHelp")) + "</p><div class=\\"cleanup-form\\">"',
    '    + "<label><span>" + safe(t("cleanupOlderThanDays")) + "</span><input id=\\"cleanup-run-older-than-days\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(settings.eligible_older_than_days || 0)) + "\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<label><span>" + safe(t("cleanupKeepLatestTasks")) + "</span><input id=\\"cleanup-run-keep-latest\\" type=\\"number\\" min=\\"0\\" value=\\"" + safe(String(settings.keep_latest_tasks || 0)) + "\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<div class=\\"action-buttons\\"><button type=\\"button\\" id=\\"cleanup-run-preview\\"" + (disabled ? " disabled" : "") + ">" + safe(t("previewCommand")) + "</button><button type=\\"button\\" id=\\"cleanup-run-apply\\"" + (disabled ? " disabled" : "") + ">" + safe(t("apply")) + "</button></div></div></section>"',
    '    + "<section class=\\"cleanup-section\\"><h3>" + safe(t("cleanupTaskPurgeTitle")) + "</h3><p class=\\"empty\\">" + safe(t("cleanupTaskPurgeHelp")) + "</p><div class=\\"cleanup-form\\">"',
    '    + "<label><span>" + safe(t("cleanupTaskId")) + "</span><input id=\\"cleanup-task-id\\" type=\\"text\\" placeholder=\\"T-123\\"" + (disabled ? " disabled" : "") + "></label>"',
    '    + "<div class=\\"action-buttons\\"><button type=\\"button\\" id=\\"cleanup-task-purge-preview\\"" + (disabled ? " disabled" : "") + ">" + safe(t("previewCommand")) + "</button><button type=\\"button\\" id=\\"cleanup-task-purge-apply\\"" + (disabled ? " disabled" : "") + ">" + safe(t("cleanupPurgeTask")) + "</button></div></div></section>"',
    '    + "</div>";',
    '  if (!disabled) {',
    '    document.getElementById("cleanup-settings-preview").addEventListener("click", () => submitCleanupSettings("preview"));',
    '    document.getElementById("cleanup-settings-save").addEventListener("click", () => submitCleanupSettings("execute"));',
    '    document.getElementById("cleanup-run-preview").addEventListener("click", () => runCleanup("preview"));',
    '    document.getElementById("cleanup-run-apply").addEventListener("click", () => runCleanup("execute"));',
    '    document.getElementById("cleanup-task-purge-preview").addEventListener("click", () => runTaskPurge("preview"));',
    '    document.getElementById("cleanup-task-purge-apply").addEventListener("click", () => runTaskPurge("execute"));',
    '  }',
    '}',
    'async function refreshCleanupSettingsPayload() {',
    '  const response = await fetch("/api/cleanup-settings");',
    '  renderCleanupSettings(await response.json());',
    '}'
].join('\n');
