import * as cliTypes from './cli-types';
import * as cliConstants from './cli-constants';
import * as cliBundleHelpers from './cli-bundle-helpers';
import * as cliSubprocessHelpers from './cli-subprocess-helpers';
import * as cliParsing from './cli-parsing';
import * as cliFormatOutput from './cli-format-output';

export type PackageJsonLike = cliTypes.PackageJsonLike;
export type HighlightedPairOptions = cliTypes.HighlightedPairOptions;
export type PromptSingleSelectOption = cliTypes.PromptSingleSelectOption;
export type PromptSingleSelectConfig = cliTypes.PromptSingleSelectConfig;
export type StatusSnapshot = cliTypes.StatusSnapshot;
export type GlobalFlags = cliParsing.GlobalFlags;

export const DEFAULT_REPO_URL = cliConstants.DEFAULT_REPO_URL;
export const SKIPPED_ENTRY_NAMES = cliConstants.SKIPPED_ENTRY_NAMES;
export const SKIPPED_FILE_SUFFIXES = cliConstants.SKIPPED_FILE_SUFFIXES;
export const DEPLOY_ITEMS = cliConstants.DEPLOY_ITEMS;
export const COMPILED_RUNTIME_DEPLOY_CANDIDATES = cliConstants.COMPILED_RUNTIME_DEPLOY_CANDIDATES;
export const COMMAND_SUMMARY = cliConstants.COMMAND_SUMMARY;

export const normalizePathValue = cliBundleHelpers.normalizePathValue;
export const toPosixPath = cliBundleHelpers.toPosixPath;
export const ensureDirectoryExists = cliBundleHelpers.ensureDirectoryExists;
export const resolvePathInsideRoot = cliBundleHelpers.resolvePathInsideRoot;
export const getBundlePath = cliBundleHelpers.getBundlePath;
export const getAgentInitPromptPath = cliBundleHelpers.getAgentInitPromptPath;
export const readOptionalJsonFile = cliBundleHelpers.readOptionalJsonFile;
export const readPackageJson = cliBundleHelpers.readPackageJson;
export const readBundleVersion = cliBundleHelpers.readBundleVersion;
export const resolveWorkspaceDisplayVersion = cliBundleHelpers.resolveWorkspaceDisplayVersion;
export const shouldSkipPath = cliBundleHelpers.shouldSkipPath;
export const copyPath = cliBundleHelpers.copyPath;
export const removePathIfExists = cliBundleHelpers.removePathIfExists;
export const ensureSourceItemExists = cliBundleHelpers.ensureSourceItemExists;
export const deployFreshBundle = cliBundleHelpers.deployFreshBundle;
export const syncBundleItems = cliBundleHelpers.syncBundleItems;

export const runProcess = cliSubprocessHelpers.runProcess;
export const acquireSourceRoot = cliSubprocessHelpers.acquireSourceRoot;

export const extractGlobalFlags = cliParsing.extractGlobalFlags;
export const parseOptions = cliParsing.parseOptions;
export const normalizeLogicalKey = cliParsing.normalizeLogicalKey;
export const getInitAnswerValue = cliParsing.getInitAnswerValue;
export const isBooleanText = cliParsing.isBooleanText;
export const parseBooleanText = cliParsing.parseBooleanText;
export const tryParseBooleanText = cliParsing.tryParseBooleanText;
export const parseOptionalText = cliParsing.parseOptionalText;
export const parseRequiredText = cliParsing.parseRequiredText;
export const normalizeSourceOfTruth = cliParsing.normalizeSourceOfTruth;
export const tryNormalizeSourceOfTruth = cliParsing.tryNormalizeSourceOfTruth;
export const normalizeAssistantBrevity = cliParsing.normalizeAssistantBrevity;
export const tryNormalizeAssistantBrevity = cliParsing.tryNormalizeAssistantBrevity;
export const convertSourceOfTruthToEntrypoint = cliParsing.convertSourceOfTruthToEntrypoint;
export const normalizeAgentEntrypointToken = cliParsing.normalizeAgentEntrypointToken;
export const normalizeActiveAgentFiles = cliParsing.normalizeActiveAgentFiles;
export const normalizeCollectedVia = cliParsing.normalizeCollectedVia;
export const readInitAnswersArtifact = cliParsing.readInitAnswersArtifact;

export const applyNoColorFlag = cliFormatOutput.applyNoColorFlag;
export const supportsColor = cliFormatOutput.supportsColor;
export const colorize = cliFormatOutput.colorize;
export const bold = cliFormatOutput.bold;
export const green = cliFormatOutput.green;
export const cyan = cliFormatOutput.cyan;
export const yellow = cliFormatOutput.yellow;
export const red = cliFormatOutput.red;
export const dim = cliFormatOutput.dim;
export const padRight = cliFormatOutput.padRight;
export const printHighlightedPair = cliFormatOutput.printHighlightedPair;
export let supportsInteractivePrompts = cliFormatOutput.supportsInteractivePrompts;
export let readLineInput = cliFormatOutput.readLineInput;
export let promptTextInput = cliFormatOutput.promptTextInput;
export let promptSingleSelect = cliFormatOutput.promptSingleSelect;
export const printBanner = cliFormatOutput.printBanner;
export const buildBannerText = cliFormatOutput.buildBannerText;
export const getStageBadge = cliFormatOutput.getStageBadge;
export const getWorkspaceHeadline = cliFormatOutput.getWorkspaceHeadline;
export const printStatus = cliFormatOutput.printStatus;
export const printCommandSummary = cliFormatOutput.printCommandSummary;
export const buildCommandSummaryLines = cliFormatOutput.buildCommandSummaryLines;
export const buildGuardedCommandHelpText = cliFormatOutput.buildGuardedCommandHelpText;
export const printHelp = cliFormatOutput.printHelp;
export const buildHelpText = cliFormatOutput.buildHelpText;
